name: Build Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # Alte Artefakte löschen
      - name: Clean old build files
        run: rm -rf release *.zip

      # Composer-Abhängigkeiten installieren
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      # Release-Ordner vorbereiten
      - name: Prepare release folder
        run: |
          mkdir release
          cp -r src vendor composer.json composer.lock release/

      # ZIP erstellen
      - name: Create archive
        run: zip -r viewports-${{ github.ref_name }}.zip release/*

      # ZIP als Release-Asset hochladen
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: viewports-${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
