name: Build plugin release .zip file

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # Alte Artefakte löschen
      - name: Clean old build files
        run: rm -rf quantum-viewports *.zip

      # Composer-Abhängigkeiten installieren
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      # Release-Ordner vorbereiten
      - name: Prepare release folder
        run: |
          mkdir quantum-viewports
          cp -r build includes src vendor languages quantum-viewports.php readme.txt quantum-viewports/

      # ZIP erstellen
      - name: Create archive
        run: zip -r quantum-viewports-plugin.zip quantum-viewports/*

      # ZIP als Release-Asset hochladen
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: quantum-viewports-plugin.zip
          token: ${{ secrets.GITHUB_TOKEN }}
